# Generated by Django 3.2.5 on 2021-12-30 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jeju_data', '0001_initial'),
        ('image', '0001_initial'),
        ('jeju', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jejuscheduledetail',
            name='acc',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='jeju_data.accommodation'),
        ),
        migrations.AddField(
            model_name='jejuscheduledetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.category'),
        ),
    ]
